// Generated by LiveScript 1.3.1
var fs, path, region, nbt, Promise, readdir, map;
fs = require('fs');
path = require('path');
region = require('./region');
nbt = require('./nbt');
Promise = require('bluebird');
readdir = Promise.promisify(fs.readdir);
map = {
  read: function(mappath){
    return readdir(path.join(mappath, 'region')).then(function(files){
      var regions;
      regions = {};
      return Promise.all(files.map(function(fn){
        var ret, ref$, x, z;
        ret = /r\.([0-9-]+)\.([0-9-]+)\.mca/.exec(fn);
        if (!ret) {
          return;
        }
        ref$ = [ret[1], ret[2]], x = ref$[0], z = ref$[1];
        return region.read(path.join(mappath, 'region', fn)).then(function(r){
          return (regions[x] || (regions[x] = {}))[z] = (r.x = x, r.z = z, r);
        });
      })).then(function(){
        return regions;
      });
    });
  },
  write: function(mappath, regions){
    var x, z;
    if (!fs.existsSync(mappath)) {
      fs.mkdirSync(mappath);
    }
    if (!fs.existsSync(path.join(mappath, 'region'))) {
      fs.mkdirSync(path.join(mappath, 'region'));
    }
    return Promise.all((function(){
      var results$ = [];
      for (x in regions) {
        for (z in regions[x]) {
          results$.push(regions[x][z]);
        }
      }
      return results$;
    }()).map(function(r){
      return region.write(path.join(mappath, 'region', "r." + r.x + "." + r.z + ".mca"), r);
    })).then(function(){
      return console.log('done');
    });
  }
};
/*
#(regions) <- map.read "/Users/tkirby/Library/Application Support/minecraft/saves/FORDEV" .then
(regions) <- map.read "/Users/tkirby/workspace/zbryikt/minecraft" .then

sections = regions[0][0].chunks[0][0].data[""]value.Level.value.Sections.value
[x,y,z] = [0,0,0]
for s in sections =>
  for y from 0 to 15 => for x from 0 to 15 => for z from 0 to 15 => s.value.Blocks[y*256 + z*16 + x] = 89
console.log "saving..."
<- map.write "/Users/tkirby/workspace/zbryikt/minecraft/out", regions .then
console.log "try read..."
(regions) <- map.read "/Users/tkirby/workspace/zbryikt/minecraft/out"
console.log "traversing..."
chunk = regions[0][0].chunks[0][0]
nbt.traverse chunk
*/
module.exports = map;