// Generated by LiveScript 1.3.1
var u2b, b2u, makebuf, b2v, v2b, b2i64, i642b;
u2b = function(str){
  return new Buffer(str, 'utf-8');
};
b2u = function(data, base, len){
  var buf;
  buf = makebuf(data, base, len);
  return buf.toString('utf-8');
};
makebuf = function(data, base, len){
  var ret, i$, i;
  ret = new Buffer(len);
  for (i$ = 0; i$ < len; ++i$) {
    i = i$;
    ret[i] = data[base + i];
  }
  return ret;
};
b2v = function(data, base, len, ret){
  var i$, i;
  ret == null && (ret = 0);
  for (i$ = 0; i$ < len; ++i$) {
    i = i$;
    ret = ret * 256 + data[base + i];
  }
  return ret;
};
v2b = function(data, base, len, value){
  var i$, i, results$ = [];
  value == null && (value = 0);
  for (i$ = len - 1; i$ >= 0; --i$) {
    i = i$;
    data[base + i] = value % 256;
    results$.push(value = value >> 8);
  }
  return results$;
};
b2i64 = function(data, base){
  var ret, i$, i;
  ret = 0;
  for (i$ = 0; i$ < 8; ++i$) {
    i = i$;
    ret = ret * 256 + data[base + i];
  }
  if (data[base] & 0x80) {
    return ~(ret - 1);
  } else {
    return ret;
  }
};
i642b = function(){};
module.exports = {
  b2u: b2u,
  u2b: u2b,
  makebuf: makebuf,
  b2v: b2v,
  b2i64: b2i64,
  i642b: i642b,
  v2b: v2b
};